{
  "number": 6413,
  "title": "NullReferenceException in SpanBasedConcatenator when evaluating target dependencies",
  "body": "Seeing this exception when building a project:\r\n\r\n```\r\nMSBUILD : error MSB1025: An internal failure occurred while running MSBuild.\r\nSystem.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Build.Evaluation.Expander`2.SpanBasedConcatenator.Add(Object obj)\r\n   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)\r\n   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)\r\n   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)\r\n   at Microsoft.Build.BackEnd.TargetEntry.GetDependencies(ProjectLoggingContext projectLoggingContext)\r\n   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__67.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__58.MoveNext()\r\n```\r\n\r\nIt does *not* repro with `16.9.0+5e4b48a27` but does with `16.10.0-preview-21181-05+80f316e90` and `16.10.0-preview-21227-06+1d1fec7c4`.\r\n\r\nI'll try to get a minimal repro, but this is happening in a private repo I'm not very familiar with. Ping me on Teams for instructions cloning the repo this is happening to in the meantime.",
  "state": "CLOSED",
  "createdAt": "2021-05-05T15:42:14Z",
  "updatedAt": "2024-02-21T14:13:37Z",
  "closedAt": "2021-05-17T15:15:26Z",
  "author": {
    "login": "dfederm"
  },
  "labels": [
    "bug",
    "regression",
    "Partner request",
    "triaged"
  ],
  "assignees": {
    "nodes": [
      {
        "login": "ladipro"
      }
    ]
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "Found a minimal repro:\r\n\r\n```xml\r\n<Project>\r\n  <Target Name=\"Build\" Condition=\"'$([System.Environment]::GetEnvironmentVariable(`Bar`))' == 'Baz'\" />\r\n</Project>\r\n```",
        "createdAt": "2021-05-05T16:15:23Z",
        "updatedAt": "2021-05-05T16:15:23Z",
        "author": {
          "login": "dfederm"
        }
      },
      {
        "body": "My best guess is that `null` should be treated as `string.Empty` in this case.",
        "createdAt": "2021-05-05T17:16:18Z",
        "updatedAt": "2021-05-05T17:16:18Z",
        "author": {
          "login": "dfederm"
        }
      }
    ]
  }
}