{
  "number": 3087,
  "title": "Exceptions thrown in EndBuild can mask failures in build",
  "body": "### Steps to reproduce\r\n\r\nThis came up when debugging #3047. Assume a bug that runs MSBuild out of memory in the command-line invocation of `ExecuteBuild`. \r\n\r\nhttps://github.com/Microsoft/msbuild/blob/06d9ad104648fbc33cdfbdd4015cdc9655bc31a2/src/MSBuild/XMake.cs#L1130-L1141\r\n\r\nThat exception is then caught and the inner `finally` runs. But if `EndBuild()` throws, _that_ exception is the one that gets logged.\r\n\r\n### Expected  behavior\r\n\r\nLog the first fatal unhandled exception, not anything that might occur when trying to do minimal cleanup.\r\n\r\nI have a fix for this, just need to put it in.",
  "state": "OPEN",
  "createdAt": "2018-03-13T22:03:27Z",
  "updatedAt": "2024-02-21T16:34:37Z",
  "closedAt": null,
  "author": {
    "login": "rainersigwald"
  },
  "labels": [
    "Area: Debuggability",
    "Area: Engine",
    "triaged"
  ],
  "assignees": {
    "nodes": [
      {
        "login": "rainersigwald"
      }
    ]
  },
  "milestone": null,
  "comments": {
    "nodes": []
  }
}