{
  "number": 10180,
  "title": "[Bug]: NRE in at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext()",
  "body": "### Issue Description\n\nMSBUILD : error : This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices\r\n.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.csproj]\r\nMSBUILD : error :     System.NullReferenceException: Object reference not set to an instance of an object. [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.\r\nUnitTests.csproj]\r\nMSBUILD : error :    at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext() [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.cspro\r\nj]\r\nMSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.cs\r\nproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests\r\n.csproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.Platf\r\normServices.UnitTests.csproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.csproj\r\n]\r\nMSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext() [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTest\r\ns.csproj]\r\nMSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.cs\r\nproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests\r\n.csproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.Platf\r\normServices.UnitTests.csproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.csproj\r\n]\r\nMSBUILD : error :    at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext() [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.cspr\r\noj]\r\nMSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.cs\r\nproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests\r\n.csproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.Platf\r\normServices.UnitTests.csproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.csproj\r\n]\r\nMSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__67.MoveNext() [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.csp\r\nroj]\r\nMSBUILD : error : --- End of stack trace from previous location where exception was thrown --- [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests.cs\r\nproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTests\r\n.csproj]\r\nMSBUILD : error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.Platf\r\normServices.UnitTests.csproj]\r\nMSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__58.MoveNext() [C:\\src\\testfx\\test\\UnitTests\\MSTestAdapter.PlatformServices.UnitTests\\MSTestAdapter.PlatformServices.UnitTest\r\ns.csproj]\n\n### Steps to Reproduce\n\nCheckout https://github.com/microsoft/testfx/pull/2973 and run `.\\Build.cmd /p:NuGetInteractive=true -pack -test -integrationTest`\n\n### Expected Behavior\n\nNo error\n\n### Actual Behavior\n\nNRE\n\n### Analysis\n\n_No response_\n\n### Versions & Configurations\n\n_No response_",
  "state": "CLOSED",
  "createdAt": "2024-05-27T15:15:40Z",
  "updatedAt": "2024-05-29T12:47:11Z",
  "closedAt": "2024-05-29T12:47:11Z",
  "author": {
    "login": "Evangelink"
  },
  "labels": [
    "bug",
    "Priority:1",
    "triaged"
  ],
  "assignees": {
    "nodes": [
      {
        "login": "ladipro"
      }
    ]
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "@Evangelink can you please add the version of MSBuild where you're hitting this? Preferably including the commit hash.",
        "createdAt": "2024-05-28T08:04:33Z",
        "updatedAt": "2024-05-28T08:04:33Z",
        "author": {
          "login": "ladipro"
        }
      },
      {
        "body": "I am using `arcade` on MSTest repo:\r\n- https://github.com/microsoft/testfx/blob/main/global.json#L13\r\n- https://github.com/microsoft/testfx/blob/main/global.json#L22\r\n\r\nFrom binlog: `MSBuild version = \"17.11.0-preview-24273-01+147ecadd1\"`",
        "createdAt": "2024-05-28T08:28:41Z",
        "updatedAt": "2024-05-28T08:28:41Z",
        "author": {
          "login": "Evangelink"
        }
      },
      {
        "body": "Thank you. This is likely related to #10102. I have recently hit the `ItemBucket.Initialize was not properly called` assert when running debug MSBuild, which I believe is the same issue, but couldn't reproduce it consistently.",
        "createdAt": "2024-05-28T09:07:57Z",
        "updatedAt": "2024-05-28T09:07:57Z",
        "author": {
          "login": "ladipro"
        }
      },
      {
        "body": "Simple repro:\r\n\r\n```xml\r\n<Project>\r\n\r\n    <ItemGroup>\r\n        <Example Include=\"Item1\">\r\n            <Color>Blue</Color>\r\n        </Example>\r\n        <Example Include=\"Item2\">\r\n            <Color>Red</Color>\r\n        </Example>\r\n    </ItemGroup>\r\n\r\n    <Target Name=\"Build\"\r\n        Inputs=\"@(Example)\"\r\n        Outputs=\"%(Color)\\MyFile.txt\">\r\n        <NonExistentTask\r\n            Text = \"@(Example)\"\r\n            Output = \"%(Color)\\MyFile.txt\"/>\r\n    </Target>\r\n\r\n</Project>\r\n```",
        "createdAt": "2024-05-29T11:28:05Z",
        "updatedAt": "2024-05-29T11:28:05Z",
        "author": {
          "login": "ladipro"
        }
      }
    ]
  }
}