{
  "number": 5296,
  "title": "NullReferenceException in TaskItem.CloneCustomMetadata",
  "body": "https://dev.azure.com/dnceng/public/_build/results?buildId=606202&view=logs&j=cb341b57-5007-5864-c16a-52e37a0ec5e0&t=c61b4578-f14d-5df9-c7d3-764b6253e0ae&l=719\r\n\r\n```\r\nMSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.\r\nMicrosoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.CloneCustomMetadata()\r\n   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)\r\n   at Microsoft.Build.Logging.BuildEventArgsWriter.WriteItems(IEnumerable items)\r\n   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ProjectStartedEventArgs e)\r\n   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(BuildEventArgs e)\r\n   at Microsoft.Build.Logging.BinaryLogger.Write(BuildEventArgs e)\r\n   at Microsoft.Build.Logging.BinaryLogger.EventSource_AnyEventRaised(Object sender, BuildEventArgs e)\r\n   at Microsoft.Build.Evaluation.ProjectCollection.ReusableLogger.AnyEventRaisedHandler(Object sender, BuildEventArgs e)\r\n   at Microsoft.Build.Framework.AnyEventHandler.Invoke(Object sender, BuildEventArgs e)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseStatusEvent(Object sender, BuildStatusEventArgs buildEvent)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseProjectStartedEvent(Object sender, ProjectStartedEventArgs buildEvent)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent, Int32 sinkId)\r\n   at Microsoft.Build.BackEnd.Logging.EventRedirectorToSink.Microsoft.Build.Framework.IEventRedirector.ForwardEvent(BuildEventArgs buildEvent)\r\n   at Microsoft.Build.BackEnd.Logging.CentralForwardingLogger.EventSource_AnyEventRaised(Object sender, BuildEventArgs buildEvent)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)\r\n```\r\n\r\n(thanks @Pilchie)",
  "state": "CLOSED",
  "createdAt": "2020-04-17T21:24:49Z",
  "updatedAt": "2024-02-21T17:04:09Z",
  "closedAt": "2020-10-02T17:22:36Z",
  "author": {
    "login": "rainersigwald"
  },
  "labels": [
    "bug",
    "Partner request",
    "triaged"
  ],
  "assignees": {
    "nodes": [
      {
        "login": "rainersigwald"
      }
    ]
  },
  "milestone": null,
  "comments": {
    "nodes": [
      {
        "body": "Possible other hit:\r\n\r\nhttps://dev.azure.com/dnceng/internal/_build/results?buildId=666725&view=logs&j=ed2c9767-8cce-57f8-db55-61577f1ca8b3&t=18691dd0-6061-5cb2-fba9-a0cfba854e8b&l=4382\r\n\r\n```\r\nBuild FAILED.\r\n\r\nF:\\workspace\\_work\\1\\s\\.packages\\microsoft.dotnet.apicompat\\5.0.0-beta.20278.4\\build\\Microsoft.DotNet.ApiCompat.targets(145,5): error MSB4181: The \"Exec\" task returned false but did not log an error. [F:\\workspace\\_work\\1\\s\\src\\libraries\\System.Security.Cryptography.Algorithms\\src\\System.Security.Cryptography.Algorithms.csproj]\r\nF:\\workspace\\_work\\1\\s\\.packages\\microsoft.dotnet.apicompat\\5.0.0-beta.20278.4\\build\\Microsoft.DotNet.ApiCompat.targets(145,5): error MSB4181: The \"Exec\" task returned false but did not log an error. [F:\\workspace\\_work\\1\\s\\src\\libraries\\System.Runtime.Serialization.Xml\\src\\System.Runtime.Serialization.Xml.csproj]\r\nF:\\workspace\\_work\\1\\s\\.packages\\microsoft.net.compilers.toolset\\3.7.0-3.20271.4\\tasks\\netcoreapp3.1\\Microsoft.CSharp.Core.targets(59,5): error MSB4181: The \"Csc\" task returned false but did not log an error. [F:\\workspace\\_work\\1\\s\\src\\libraries\\System.Security.Cryptography.Algorithms\\src\\System.Security.Cryptography.Algorithms.csproj]\r\n    0 Warning(s)\r\n    3 Error(s)\r\n\r\nTime Elapsed 00:14:56.82\r\nMSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.\r\nMicrosoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure.\r\n ---> System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.CloneCustomMetadata()\r\n   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)\r\n   at Microsoft.Build.Logging.BuildEventArgsWriter.WriteItems(IEnumerable items)\r\n   at Microsoft.Build.Logging.BinaryLogger.Write(BuildEventArgs e)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)\r\n```",
        "createdAt": "2020-06-01T18:01:44Z",
        "updatedAt": "2020-06-01T18:01:44Z",
        "author": {
          "login": "rainersigwald"
        }
      },
      {
        "body": "Just hit this again here.  https://dev.azure.com/dnceng/public/_build/results?buildId=727755&view=logs&j=da3b6fae-2b9c-515e-f961-941b19f305e4&t=e211c71e-116d-5222-99f8-68e08c58ca66\r\n\r\ncc @maryamariyan\r\n\r\n```\r\nMSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.\r\nMicrosoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure.\r\n ---> System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.CloneCustomMetadata()\r\n   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item)\r\n   at Microsoft.Build.Logging.BuildEventArgsWriter.WriteItems(IEnumerable items)\r\n   at Microsoft.Build.Logging.BinaryLogger.Write(BuildEventArgs e)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)\r\n   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)\r\n```",
        "createdAt": "2020-07-14T01:07:02Z",
        "updatedAt": "2020-07-14T01:07:02Z",
        "author": {
          "login": "ericstj"
        }
      },
      {
        "body": "@rainersigwald confirm if your copy on write dictionary changes updated this.",
        "createdAt": "2020-10-02T17:18:21Z",
        "updatedAt": "2020-10-02T17:18:21Z",
        "author": {
          "login": "marcpopMSFT"
        }
      },
      {
        "body": "Optimistically closing this hoping that the `ImmutableDictionary` change in #5279 fixes it. If you see this on 16.8+, please comment and we can reopen.",
        "createdAt": "2020-10-02T17:22:36Z",
        "updatedAt": "2020-10-02T17:22:36Z",
        "author": {
          "login": "rainersigwald"
        }
      }
    ]
  }
}