{
  "number": 8069,
  "title": "Avoid losing the exception stack in BuildManager.EndBuild",
  "body": "While investigating a flaky unit test I noticed the exception stack trace was basically useless:\r\n\r\nStack trace:\r\n```\r\n   at Microsoft.Build.Execution.BuildManager.EndBuild() in /_/src/Build/BackEnd/BuildManager/BuildManager.cs:line 963\r\n   at Microsoft.Build.UnitTests.Helpers.BuildManagerSession.Dispose() in D:\\a\\1\\s\\src\\Shared\\UnitTests\\ObjectModelHelpers.cs:line 2104\r\n   at Microsoft.Build.Engine.UnitTests.ProjectCache.ProjectCacheTests.MultiplePlugins() in D:\\a\\1\\s\\src\\Build.UnitTests\\ProjectCache\\ProjectCacheTests.cs:line 1049\r\n```\r\n\r\nThis is due to rethrowing the exception incorrectly (`throw e;` vs `throw;`). Looks like this was done in order to flatten an `AggregateException`, but the original stack trace can be preserved there as well using `ExceptionDispatchInfo`.",
  "state": "MERGED",
  "createdAt": "2022-10-17T16:22:44Z",
  "updatedAt": "2022-10-21T07:33:38Z",
  "closedAt": "2022-10-21T07:33:37Z",
  "mergedAt": "2022-10-21T07:33:37Z",
  "additions": 2,
  "deletions": 2,
  "changedFiles": 1,
  "headRefName": "buildmanager-endbuild-capture-stack",
  "isDraft": false,
  "author": {
    "login": "dfederm"
  },
  "milestone": null,
  "assignees": {
    "nodes": []
  },
  "labels": [
    "merge-when-branch-open"
  ],
  "commits": {
    "nodes": [
      {
        "commit": {
          "oid": "941a00622d1e6cb1e9074ab98f97abd6a6e3d1f0",
          "message": "Avoid losing the exception stack in BuildManager.EndBuild",
          "committedDate": "2022-10-17T16:16:21Z",
          "author": {
            "name": "David Federman",
            "email": "dfederm@microsoft.com"
          }
        }
      }
    ]
  },
  "comments": {
    "nodes": []
  },
  "reviewThreads": {
    "nodes": []
  }
}