{
  "number": 8000,
  "title": "Fallback when server launch fail due to create mutex error",
  "body": "Fixes #7993, https://github.com/dotnet/runtime/issues/75867\r\n\r\n### Context\r\nThere were reported issues, when mutex logic failed with unhandled IOException.\r\n\r\n### Changes Made\r\nExtend TryLaunchServer try-catch scope to Include opening mutex and if it throws fallback to non-server behavior.\r\n\r\n### Testing\r\nUnit test, CI.\r\n",
  "state": "MERGED",
  "createdAt": "2022-09-22T11:57:23Z",
  "updatedAt": "2022-10-05T16:19:09Z",
  "closedAt": "2022-09-24T19:36:41Z",
  "mergedAt": "2022-09-24T19:36:41Z",
  "additions": 15,
  "deletions": 14,
  "changedFiles": 1,
  "headRefName": "rokonec/7993-server-fallback-on-mutex-exception",
  "isDraft": false,
  "author": {
    "login": "rokonec"
  },
  "milestone": null,
  "assignees": {
    "nodes": []
  },
  "labels": [
    "merge-when-branch-open"
  ],
  "commits": {
    "nodes": [
      {
        "commit": {
          "oid": "d3e3f40bb771d18bdb93444f53880fd005a04371",
          "message": "Fallback when server launch fail due to create mutex error",
          "committedDate": "2022-09-22T11:51:10Z",
          "author": {
            "name": "Roman Konecny",
            "email": "rokonecn@microsoft.com"
          }
        }
      }
    ]
  },
  "comments": {
    "nodes": [
      {
        "body": "@rokonec we want this in asap I think and flowing to an rtm sdk build that other teams can try.",
        "createdAt": "2022-09-23T21:27:41Z",
        "author": {
          "login": "marcpopMSFT"
        }
      },
      {
        "body": "Looks like you're closing the runtime repo bug. Do we still need a bug to figure out why it's timing out? Someone else mentioned it wasn't documented.",
        "createdAt": "2022-09-23T22:03:43Z",
        "author": {
          "login": "danmoseley"
        }
      },
      {
        "body": "I feel confident about those changes so I will go ahead and merge it now.\r\n",
        "createdAt": "2022-09-24T19:36:34Z",
        "author": {
          "login": "rokonec"
        }
      },
      {
        "body": "@danmoseley \r\n> Do we still need a bug to figure out why it's timing out?\r\n\r\nI would still like to know root cause. Yes it is not documented why would creating named mutex throw IOException with \"Timeout\" message. I think it might deserve investigation to better understand severity of this.",
        "createdAt": "2022-09-24T19:39:53Z",
        "author": {
          "login": "rokonec"
        }
      },
      {
        "body": "It would be great if you could open a runtime repo bug describing the configurations where you've seen this. Even if it's not actionable right now.",
        "createdAt": "2022-10-05T15:45:29Z",
        "author": {
          "login": "danmoseley"
        }
      },
      {
        "body": "> It would be great if you could open a runtime repo bug describing the configurations where you've seen this. Even if it's not actionable right now.\r\n\r\nYes, @rokonec is on it.",
        "createdAt": "2022-10-05T16:19:09Z",
        "author": {
          "login": "AR-May"
        }
      }
    ]
  },
  "reviewThreads": {
    "nodes": []
  }
}